---
apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  name: johndoe3-gcp
  namespace: garden-icke
spec:
  cloud:
    profile: gcp
    region: europe-west3
    secretBindingRef:
      name: trial-secret-gcp
    gcp:
    # machineImage: # this machine image is default machine image for all worker pools
    #   name: coreos
    #   version: 2023.5.0
      networks:
      # vpc:
      #   name: my-vpc
        internal: 10.250.112.0/22
        workers: ['10.250.0.0/19']
      workers:
      - name: cpu-worker
        machineType: n1-standard-4
        volumeType: pd-standard
        volumeSize: 20Gi
        autoScalerMin: 2
        autoScalerMax: 2
        maxSurge: 1
        maxUnavailable: 0
      zones: ['europe-west3-b']
  kubernetes:
    version: 1.15.2
    allowPrivilegedContainers: true # 'true' means that all authenticated users can use the "gardener.privileged" PodSecurityPolicy, allowing full unrestricted access to Pod features.

  dns:
  # # provider: aws-route53
  #   domain: johndoe2-gcp.icke.shoot.canary.k8s-hana.ondemand.com
# hibernation:
#   enabled: false
#   schedules:
#   - start: "0 20 * * *" # Start hibernation every day at 8PM
#     end: "0 6 * * *"    # Stop hibernation every day at 6AM
#     location: "America/Los_Angeles" # Specify a location for the cron to run in
  maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
  # Backup configuration for Shoot clusters is deprecated and no longer supported.
  # The responsibility for these settings has been shifted to Garden administrators.
  # This field will be removed in the future and is only kept for API compatibility reasons. It is not
  # evaluated or respected at all. Please do not use this field anymore.
  backup:
    schedule: "0 */24 * * *"
    maximum: 7
  addons:
    # nginx-ingress addon is still supported but deprecated.
    # This field will be removed in the future. You should deploy your own ingress controller
    # instead of enabling it here. You should not use this field anymore.
    nginx-ingress:
      enabled: false
      loadBalancerSourceRanges: []
    kubernetes-dashboard:
      enabled: true
   
